name: Deploy Node.js App to Azure Web App from Artefactory

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-artifact
          path: .

      - name: Extract and Deploy
        run: |
          tar -xzvf webapp-*.tar.gz
          echo "Deploying to Azure App Service"
          az webapp deploy --resource-group DevOpsLearning --name WebApp-CICD-Agile --src-path . --type zip --restart true    
