name: Deploy Node.js App to Azure Web App from Artifact

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: 'ID of the build workflow run to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    environment:
      name: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "GitHub CLI authenticated"

      - name: Download Artifact from CI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir downloaded
          gh run download ${{ github.event.inputs.build_run_id }} -n webapp-artifact -D downloaded

      - name: List Downloaded Files
        run: ls -lh downloaded

      - name: Extract and Deploy
        run: |
          tar -xzvf downloaded/webapp-*.tar.gz
          echo "Deploying to Azure App Service"
          az webapp deploy \
            --resource-group DevOpsLearning \
            --name WebApp-CICD-Agile \
            --src-path . \
            --type zip \
            --restart true
